### ISSUE TITLE
Database documentation 

### ISSUE THREAD

**Issue by XOR-SABER** [slariosjr/CST438-Project1#7]
As a developer, the Database should be well documented, and in a ER diagram and in 3NF form for ease of use!

☆*: .｡. o(≧▽≦)o .｡.:*☆

**Comment by slariosjr** [comment]
![Untitled diagram-2024-09-03-132821](https://github.com/user-attachments/assets/58fe4e0c-7612-416a-a363-b1fc7f7519f6)


ER diagram for the database. Will update as needed.

**Comment by slariosjr** [comment]
![Untitled diagram-2024-09-03-132821](https://github.com/user-attachments/assets/9c29c1f5-09ec-405a-85be-b2a5c2b87c9d)


ER Diagram for the database. WIll update as needed.
